name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Tasks Check
      id: tasks-check
      uses: education/autograding-command-grader@v1
      with:
        test-name: Tasks Check
        setup-command: npm install
        command: npm test
        timeout: 3
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TASKS-CHECK_RESULTS: "${{steps.tasks-check.outputs.result}}"
      with:
        runners: tasks-check
